name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
    - uses: actions/checkout@v2
    - name: Compile LaTex document (fast)
    - uses: repaction/texlive@main
      with:
        tex_files: |
          main.tex
   - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: main.pdf
        path: main.pdf
